version: "3"
services:
  mysql:
    image: mysql:10-alpine
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5432:${MYSQL_PORT}"
volumes:
  mysql:
